spring:
#  zipkin:
#    base-url: http://39.107.24.27:41202
#   如果是测试环境则dev_model=true 不做验证码校验，自定义的属性
  dev_model: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  session:
    store-type: redis
  redis:
    database: 0
    host: 127.0.0.1
    password: Neco.wosh77@0217*$%
    port: 43709
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        #注册服务时使用ip地址而不是主机名
        prefer-ip-address: true
        #唯一的服务实例ID
        #ID默认为${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    inetutils:
      # 优先使用以192.168.开头的IP去注册中心注册
      preferred-networks:
        - ^192\.168.*
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
